import { chromium } from 'playwright';
const U='https://shared-docs-thenatas-projects.vercel.app';
const b=await chromium.launch(); const ctx=await b.newContext({viewport:{width:1600,height:900}});
const p=await ctx.newPage();
const s=async(l,f)=>{process.stdout.write(`${l} ... `);try{await f();console.log('ok')}catch(e){console.log('FAIL: '+e.message.split('\n')[0])}};
await p.goto(`${U}/login`); await p.getByRole('button',{name:/alice/i}).first().click();
await p.waitForURL('**/documents'); await p.getByText('Q3 Product Roadmap').first().waitFor({timeout:30000});
await s('import sample.md', async()=>{
  await p.locator('input[type=file]').first().setInputFiles('../samples/sample.md');
  await p.waitForURL(/\/documents\/[^/]+$/,{timeout:40000});
  await p.locator('.ProseMirror').waitFor({timeout:30000});
});
await p.waitForTimeout(2000);
console.log('  url:', p.url());
console.log('  share trigger count:', await p.getByRole('button',{name:/^share$/i}).count());
console.log('  ALL buttons:', await p.$$eval('button', ns=>ns.map(n=>JSON.stringify(n.innerText.trim()||n.getAttribute('aria-label'))).join(' ')));
await s('click trigger', async()=>{ await p.getByRole('button',{name:/^share$/i}).first().click({timeout:8000}); });
await p.waitForTimeout(1500);
const dlg=p.locator('[role=dialog]');
console.log('  dialog visible:', await dlg.isVisible().catch(()=>false));
await s('type email', async()=>{ const e=dlg.locator('input[placeholder="Email address"]'); await e.click({timeout:8000}); await e.type('carol@example.com',{delay:15}); });
await p.waitForTimeout(500);
await s('open role select', async()=>{ await dlg.locator('button[aria-label="Role for the person you are inviting"]').click({timeout:8000}); });
await p.waitForTimeout(1000);
console.log('  options on page:', await p.$$eval('[role=option]', ns=>ns.map(n=>JSON.stringify(n.innerText.trim())).join(' ')) );
await s('pick Viewer', async()=>{ await p.getByRole('option',{name:/viewer/i}).first().click({timeout:8000}); });
await p.waitForTimeout(800);
await s('click Share submit', async()=>{ await dlg.getByRole('button',{name:/^share$/i}).first().click({timeout:8000}); });
await p.waitForTimeout(2500);
console.log('  dialog rows now:', await p.$$eval('[role=dialog] button[aria-label^="Role for"]', ns=>ns.map(n=>n.getAttribute('aria-label')+'='+n.innerText.trim()).join(' | ')).catch(()=>'n/a'));
await p.screenshot({path:'../screenshots/probe-share-done.png'});
await b.close();
